"""Install, relocate and audit the private STAR distribution."""
import argparse
import os
from pathlib import Path
import platform
import shutil
import subprocess
import tempfile
import tarfile

from smoke import run, smoke


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--build', type=Path, required=True)
    parser.add_argument('--cmake', required=True)
    parser.add_argument('--libexec', default='libexec')
    parser.add_argument('--bindir', default='bin')
    parser.add_argument('--datadir', default='share')
    parser.add_argument('--static', action='store_true')
    parser.add_argument('--archive', type=Path, help='Validate a CPack TGZ instead of installing')
    args = parser.parse_args()
    build = args.build.resolve()
    with tempfile.TemporaryDirectory(prefix='rnanue STAR package ') as temporary:
        root = Path(temporary)
        installed = root / 'relocated package'
        if args.archive:
            unpacked = root / 'unpacked'
            with tarfile.open(args.archive) as archive:
                # The archive is generated by this test's own CPack build.
                archive.extractall(unpacked, filter='data')
            packages = list(unpacked.iterdir())
            assert len(packages) == 1, packages
            shutil.move(packages[0], installed)
        else:
            env = dict(os.environ, DESTDIR=str(root / 'stage'))
            run([args.cmake, '--install', build, '--prefix', '/rnanue'], env=env)
            shutil.move(root / 'stage/rnanue', installed)
        star = installed / args.libexec / 'rnanue/STAR'
        locator = installed / args.bindir / 'star_locator_probe'
        assert os.access(star, os.X_OK)
        assert Path(run([locator], cwd=root).stdout.strip()).resolve() == star.resolve()
        notices = installed / args.datadir / 'rnanue/licenses/STAR'
        for name in ['LICENSE', 'upstream-source.tar.gz', 'build-info.txt',
                     'GCC-RUNTIME-EXCEPTION.txt', 'GPL-3.0.txt', 'zlib-notice.h']:
            assert (notices / name).is_file(), name
        metadata = (notices / 'build-info.txt').read_text()
        assert 'commit=b1edc1208d91a53bf40ebae8669f71d50b994851' in metadata
        # Check the actual native architecture, not just the recorded metadata.
        kind = run(['/usr/bin/file', star]).stdout.lower()
        machine = platform.machine().lower()
        expected = ('arm64', 'aarch64') if machine in ('arm64', 'aarch64') else ('x86-64', 'x86_64')
        assert any(arch in kind for arch in expected), kind
        # macOS archives may carry AppleDouble metadata beside the actual files.
        binaries = [star] + [p for p in (star.parent / 'lib').glob('*')
                             if not p.name.startswith('._')]
        if platform.system() == 'Darwin':
            for binary in binaries:
                output = run(['/usr/bin/otool', '-L', binary]).stdout
                for line in output.splitlines()[1:]:
                    dependency = line.strip().split(' (compatibility')[0]
                    assert dependency.startswith(('/usr/lib/', '/System/Library/', '@loader_path/')), output
                    if dependency.startswith('@loader_path/'):
                        assert (binary.parent / dependency[len('@loader_path/'):]).exists(), dependency
                run(['/usr/bin/codesign', '--verify', binary])
                assert 'LC_RPATH' not in run(['/usr/bin/otool', '-l', binary]).stdout
        elif args.static:
            assert 'statically linked' in kind, kind
            headers = run(['readelf', '-l', star]).stdout
            assert 'INTERP' not in headers
        else:
            for binary in binaries:
                result = run(['ldd', binary]).stdout
                assert 'not found' not in result, result
                for line in result.splitlines():
                    if '=>' not in line:
                        continue
                    name, location = line.split('=>', 1)
                    system = name.strip().split('.so')[0] in {
                        'libc', 'libm', 'libpthread', 'libdl', 'librt', 'libresolv', 'libutil'}
                    assert system or str(star.parent / 'lib') in location, result
        # Run with loader environment and user PATH stripped. Genome/mapping smoke
        # uses uncompressed input so it needs no external decompressor.
        saved = dict(os.environ)
        try:
            for key in list(os.environ):
                if key.startswith(('DYLD_', 'LD_', 'CONDA')):
                    os.environ.pop(key)
            os.environ['PATH'] = '/usr/bin:/bin'
            smoke(star)
        finally:
            os.environ.clear()
            os.environ.update(saved)
        # A missing installed executable must not fall back to the build or PATH.
        star.rename(star.with_suffix('.hidden'))
        missing = subprocess.run([str(locator)], text=True, capture_output=True, timeout=10)
        assert missing.returncode != 0 and 'missing or not executable' in missing.stderr
        assert str(build) not in missing.stderr, missing.stderr
    print('STAR staged install, relocation, dependencies, notices and missing-file diagnostics passed')


if __name__ == '__main__':
    main()
