include(ExternalProject)
include(${CMAKE_CURRENT_LIST_DIR}/dependency_providers.cmake)

set(RNANUE_TBB_VERSION "2022.0.0" CACHE STRING "oneTBB version to build when TBB is not installed")
set(RNANUE_TBB_PREFIX "${CMAKE_BINARY_DIR}/submodules/tbb-prefix")
set(RNANUE_TBB_INSTALL "${CMAKE_BINARY_DIR}/submodules/tbb-install")
set(RNANUE_TBB_INCLUDE_DIR "${RNANUE_TBB_INSTALL}/include")
set(RNANUE_TBB_LIBRARY_DIR "${RNANUE_TBB_INSTALL}/lib")
set(RNANUE_TBB_LIBRARY "${RNANUE_TBB_LIBRARY_DIR}/${CMAKE_SHARED_LIBRARY_PREFIX}tbb${CMAKE_SHARED_LIBRARY_SUFFIX}")

file(MAKE_DIRECTORY "${RNANUE_TBB_INCLUDE_DIR}")
file(MAKE_DIRECTORY "${RNANUE_TBB_LIBRARY_DIR}")

ExternalProject_Add(
    RNAnue_tbb
    PREFIX "${RNANUE_TBB_PREFIX}"
    DOWNLOAD_EXTRACT_TIMESTAMP true
    URL "https://github.com/oneapi-src/oneTBB/archive/refs/tags/v${RNANUE_TBB_VERSION}.tar.gz"
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_INSTALL_PREFIX=${RNANUE_TBB_INSTALL}
        -DCMAKE_INSTALL_LIBDIR=lib
        -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        -DTBB4PY_BUILD=OFF
        -DTBBMALLOC_BUILD=OFF
        -DTBBMALLOC_PROXY_BUILD=OFF
        -DTBB_DISABLE_HWLOC_AUTOMATIC_SEARCH=ON
        -DTBB_ENABLE_IPO=OFF
        -DTBB_EXAMPLES=OFF
        -DTBB_INSTALL=ON
        -DTBB_TEST=OFF
        -DTBB_STRICT=OFF
)

add_library(TBB::tbb UNKNOWN IMPORTED GLOBAL)
set_target_properties(TBB::tbb PROPERTIES
    IMPORTED_LOCATION "${RNANUE_TBB_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${RNANUE_TBB_INCLUDE_DIR}"
)

rnanue_record_dependency("oneTBB" "${RNANUE_TBB_PROVIDER}" "${RNANUE_TBB_INCLUDE_DIR}" "${RNANUE_TBB_LIBRARY}")
